--3. What is the most viewed show on ABC channel?

SELECT c.CHANNEL_NAME, c.SHOW_NAME, SUM(v.VIEWER_NUM) as VIEWER_COUNT 
FROM (SELECT DISTINCT CHANNEL_NAME, SHOW_NAME FROM TV_SHOW_CHANNEL) c INNER JOIN TV_SHOW_VIEWER v ON (c.SHOW_NAME = v.SHOW_NAME) 
WHERE c.CHANNEL_NAME = 'ABC' 
GROUP BY c.CHANNEL_NAME, c.SHOW_NAME 
ORDER BY VIEWER_COUNT DESC LIMIT 1;

/*

=======
Result:
=======

ABC	Hourly_Talking	108163

*/


